name: cellrank_reproducibility
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - cryptography=3.1.1
  - fontconfig=2.13.1
  - freetype=2.10.3
  - gettext=0.19.8.1
  - glib=2.66.1
  - gmp=6.2.0
  - gprofiler-official=1.0.0
  - hdf5=1.10.6
  - hypre=2.18.2
  - icu=67.1
  - idna=2.10
  - leidenalg=0.8.2
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcxx=11.0.0
  - libffi=3.2.1
  - libiconv=1.16
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libxml2=2.9.10
  - llvm-openmp=11.0.0
  - metis=5.1.0
  - mpi=1.0
  - mpich=3.3.2
  - mumps-include=5.2.1=8
  - mumps-mpi=5.2.1
  - ncurses=6.2
  - numpy=1.19.2
  - openssl=1.1.1h
  - parmetis=4.0.3
  - pcre=8.44
  - petsc=3.13.6
  - petsc4py=3.13.0
  - pip=20.2.3
  - pixman=0.38.0
  - ptscotch=6.0.9
  - pycairo=1.20.0
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.8.6
  - python-igraph=0.8.3
  - python_abi=3.8=1_cp38
  - readline=8.0
  - requests=2.24.0
  - scalapack=2.0.2
  - scotch=6.0.9
  - setuptools=49.6.0
  - six=1.15.0
  - slepc=3.13.4
  - slepc4py=3.13.0
  - sqlite=3.33.0
  - suitesparse=5.6.0
  - superlu=5.2.1
  - superlu_dist=6.2.0
  - tbb=2019.9
  - texttable=1.6.3
  - tk=8.6.10
  - urllib3=1.25.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - r-base
  - pip:
    - memory_profiler==0.57.0
    - cloudpickle==1.6.0
    - absl-py==0.10.0
    - anndata==0.7.4
    - appdirs==1.4.4
    - appnope==0.1.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.2.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cfgv==3.2.0
    - click==7.1.2
    - compress-pickle==1.1.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - distlib==0.3.1
    - docrep==0.3.1
    - entrypoints==0.3
    - filelock==3.0.12
    - future==0.18.2
    - future-fstrings==1.2.0
    - get-version==2.1
    - h5py==2.10.0
    - identify==1.5.6
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jax==0.2.3
    - jaxlib==0.1.56
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.17.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - kiwisolver==1.2.0
    - legacy-api-wrap==1.2
    - llvmlite==0.34.0
    - loompy==3.0.6
    - markupsafe==1.1.1
    - matplotlib==3.3.2
    - mistune==0.8.4
    - natsort==7.0.1
    - nbclient==0.5.0
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.1
    - networkx==2.5
    - nodeenv==1.5.0
    - notebook==6.1.4
    - numba==0.51.2
    - numexpr==2.7.1
    - numpy-groupies==0.9.13
    - opt-einsum==3.3.0
    - packaging==20.4
    - pandas==1.1.3
    - pandocfilters==1.4.2
    - parso==0.7.1
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.0
    - pre-commit==2.7.1
    - progressbar2==3.53.1
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.8
    - ptyprocess==0.6.0
    - pygam==0.8.0
    - pygments==2.7.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - python-utils==2.4.0
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - scanpy==1.6.0
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - seaborn==0.11.0
    - send2trash==1.5.0
    - setuptools-scm==4.1.2
    - sinfo==0.3.1
    - statsmodels==0.12.0
    - stdlib-list==0.7.0
    - tables==3.6.1
    - terminado==0.9.1
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - toml==0.10.1
    - tornado==6.0.4
    - tqdm==4.50.2
    - traitlets==5.0.4
    - tzlocal==2.1
    - umap-learn==0.4.6
    - vendorize==0.2.1
    - virtualenv==20.0.34
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - anndata2ri==1.0.4

