name: cellrank_reproducibility_updated
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cellrank-krylov=1.0.0
  - gprofiler-official=1.0.0
  - hdf5=1.10.6
  - igraph=0.8.3
  - leidenalg=0.8.2
  - louvain=0.6.1
  - mpi=1.0
  - mpich=3.3.2
  - numpy=1.19.2
  - petsc=3.13.6
  - petsc4py=3.13.0
  - python=3.8.6
  - python-igraph
  - r-base=4.0.3
  - rpy2=3.3.2
  - slepc=3.13.4
  - slepc4py=3.13.0
  - pip:
    - anndata==0.7.4
    - bezier==2020.5.19
    - h5py==2.10.0
    - jax==0.2.3
    - jaxlib==0.1.56
    - loompy==3.0.6
    - matplotlib==3.3.2
    - networkx==2.5
    - numba==0.51.2
    - palantir==1.0.0
    - pandas==1.1.3
    - phenograph==1.5.7
    - pydtmc==4.9.0
    - pygam==0.8.0
    - scanpy==1.6.0
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - seaborn==0.11.0
    - statsmodels==0.12.0
    - umap-learn==0.4.6
    - vendorize==0.2.1
    - scvelo==0.2.2
